# site properties and page defaults
title: Huminex
subtitle: 
description: >
  The Huminex lab is a research group deeply committed to exploring how intelligent technologies can responsibly enhance human emotion, cognition, and behavior. The lab grew out of an
  student-led human-centered computing club started by Lili Zhang during her undergraduate years at Hainan University.
  Our mission is to designing adaptive and embodied systems to ethically intervene in human experience without diminishing autonomy, to enhance well-being and promote equitable human–
  technology futures.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@ivioletsss.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: ivioletsss
  twitter: ivioletsss
  youtube: ivioletsss

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
